name: qra
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_remix: ^0.0.3
  lottie: ^1.2.1
  cupertino_icons: ^1.0.2
  dismissible_page: ^0.7.3
  jiffy: ^5.0.0
  flutter_platform_widgets: ^1.20.0
  flutter_feather_icons: ^2.0.0+1
  freezed: ^0.14.1+1
  get: ^4.6.5
  dartz: ^0.10.0
  shared_preferences: ^2.0.8
  url_launcher: ^6.1.2

  #Local auth
  local_auth: ^1.1.6

  #firebase
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6

  #google font
  google_fonts: ^3.0.1

  #device preview
  device_preview: ^1.0.0

  #QR
  qr_flutter: ^4.0.0
  mobile_scanner: ^1.1.2

  # State Management
  hooks_riverpod: ^1.0.0
  flutter_hooks: ^0.18.0

  #UI
  slide_to_confirm: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # No version number means the latest version
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.1
  json_serializable: ^6.1.4
  http:

  #generating icons
  flutter_launcher_icons: "^0.10.0"

#dependency_overrides:
#  analyzer: ^4.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon2.png"

flutter_native_splash:
  android: true
  ios: true
  web: false

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
